# This file lists the dependencies needed to build and test all of
# unique-factory.
# Create a conda environment with these dependencies preinstalled with:
# conda env create -f environment.yml
name: unique-factory-build
channels:
  - conda-forge
  - defaults
dependencies:
  - automake
  - benchmark
  - coreutils
  - cxx-compiler
  - libtool
  - make
  # valgrind is only needed for make check-valgrind
  # - valgrind
