name: Test
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-unique-factory:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target:
          - check
          - check-valgrind
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - name: install valgrind and libc debug symbols
        run: sudo apt install libc6-dbg valgrind
        if: ${{ matrix.target == 'check-valgrind' }}
      - uses: conda-incubator/setup-miniconda@v2
        with: { miniforge-variant: "Mambaforge", miniforge-version: "latest" }
      - name: install dependencies
        shell: bash -l {0}
        run: |
          mamba env update --quiet -n test -f environment.yml
          conda list
      - name: make ${{ matrix.target }}
        shell: bash -l {0}
        run: |
          ./bootstrap
          export CXXFLAGS="$CXXFLAGS -UNDEBUG"
          ./configure --prefix="$PREFIX" --without-benchmark --without-doc
          make
          make V=1 ${{ matrix.target }}
      - uses: flatsurf/actions/show-logs@main
        if: ${{ always() }}
  distcheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: conda-incubator/setup-miniconda@v2
        with: { miniforge-variant: "Mambaforge", miniforge-version: "latest" }
      - name: install dependencies
        shell: bash -l {0}
        run: |
          mamba env update --quiet -n test -f environment.yml
          conda list
      - name: make distcheck
        shell: bash -l {0}
        run: |
          ./bootstrap
          ./configure --prefix="$PREFIX"
          EXTRA_STANDARDESE_FLAGS=-I${CONDA_PREFIX}/include make distcheck
      - uses: flatsurf/actions/show-logs@main
        if: ${{ always() }}

env:
  MAKEFLAGS: -j2
